// Script para extrair veículos da Renatinhu's Cars
// Dados extraídos manualmente do site em 2025-11-14

export const renatinhuVehicles = [
  {
    marca: 'BMW',
    modelo: '125I',
    versao: '2.0 M SPORT 16V',
    ano: 2014,
    km: 85840,
    preco: 85000, // Estimado
    cor: 'Prata',
    carroceria: 'Hatch',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'BMW 125i M Sport, veículo premium com ótimo desempenho',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_661_1-1.jpg',
  },
  {
    marca: 'BMW',
    modelo: 'X5',
    versao: '3.0 SI 4X4 24V',
    ano: 2010,
    km: 166952,
    preco: 75000,
    cor: 'Preto',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV premium BMW X5, espaçosa e potente',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_735_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Celta',
    versao: '1.0 MPFI LIFE 8V',
    ano: 2011,
    km: 178796,
    preco: 18000,
    cor: 'Branco',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    descricao: 'Econômico e ideal para o dia a dia',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_731_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cobalt',
    versao: '1.8 MPFI LTZ 8V',
    ano: 2016,
    km: 193527,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan completo, confortável e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_760_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Corsa',
    versao: '1.0 MPFI JOY 8V',
    ano: 2007,
    km: 192805,
    preco: 16000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    descricao: 'Compacto e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_593_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Corsa Pick-up',
    versao: '1.6 MPFI ST CS',
    ano: 2003,
    km: 190999,
    preco: 20000,
    cor: 'Branco',
    carroceria: 'Picape',
    combustivel: 'Gasolina',
    cambio: 'Manual',
    arCondicionado: false,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    descricao: 'Picape compacta ideal para trabalho',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_607_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cruze',
    versao: '1.8 LT 16V',
    ano: 2012,
    km: 160132,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan médio completo e confortável',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_749_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'Onix',
    versao: '1.0 LS MT',
    ano: 2016,
    km: 158662,
    preco: 39000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Compacto moderno e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_727_1-1.jpg',
  },
  {
    marca: 'Chevrolet',
    modelo: 'S10',
    versao: '2.4 MPFI RODEIO 4X2 CD',
    ano: 2011,
    km: 153329,
    preco: 48000,
    cor: 'Preto',
    carroceria: 'Picape',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Picape cabine dupla, robusta e versátil',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_695_1-1.jpg',
  },
  {
    marca: 'Dodge',
    modelo: 'Journey',
    versao: '3.6 RT V6 24V',
    ano: 2013,
    km: 150,
    preco: 62000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV 7 lugares, espaçoso e confortável',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_691_1-1.jpg',
  },
  {
    marca: 'Fiat',
    modelo: 'Doblo',
    versao: '1.8 MPI ESSENCE 7L 16V',
    ano: 2017,
    km: 110221,
    preco: 45000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Minivan 7 lugares, ideal para famílias',
  },
  {
    marca: 'Fiat',
    modelo: 'Palio',
    versao: '1.4 MPI ATTRA 8V',
    ano: 2014,
    km: 146386,
    preco: 28000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Compacto confiável e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_717_1-1.jpg',
  },
  {
    marca: 'Fiat',
    modelo: 'Siena',
    versao: 'EL 1.0',
    ano: 2013,
    km: 168338,
    preco: 26000,
    cor: 'Branco',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: false,
    descricao: 'Sedan econômico e espaçoso',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_732_1-1.jpg',
  },
  {
    marca: 'Fiat',
    modelo: 'Strada',
    versao: '1.8 MPI ADVENT CE 8V',
    ano: 2010,
    km: 195953,
    preco: 32000,
    cor: 'Branco',
    carroceria: 'Picape',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    descricao: 'Picape compacta, ideal para trabalho',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_708_1-1.jpg',
  },
  {
    marca: 'Fiat',
    modelo: 'Uno',
    versao: '1.0 WAY 8V',
    ano: 2021,
    km: 72406,
    preco: 48000,
    cor: 'Branco',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Compacto moderno, baixa quilometragem',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_739_1-1.jpg',
  },
  {
    marca: 'Ford',
    modelo: 'Ka+',
    versao: '1.0 TI-VCT SE PLUS',
    ano: 2018,
    km: 140,
    preco: 42000,
    cor: 'Branco',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan compacto, praticamente zero km',
  },
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V',
    ano: 2016,
    km: 102971,
    preco: 52000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan médio confortável e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_715_1-1.jpg',
  },
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V',
    ano: 2013,
    km: 189091,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan médio Honda, confiável',
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXL 16V',
    ano: 2012,
    km: 187268,
    preco: 48000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan médio, conforto e qualidade Honda',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_754_1-1.jpg',
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXS 16V',
    ano: 2010,
    km: 139562,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Clássico Civic, confiável e econômico',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_682_1-1.jpg',
  },
  {
    marca: 'Honda',
    modelo: 'CR-V',
    versao: 'EX 2.0',
    ano: 2007,
    km: 168234,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV confiável Honda CR-V',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_658_1-1.jpg',
  },
  {
    marca: 'Hyundai',
    modelo: 'Creta',
    versao: '1.6 16V ATTITUDE',
    ano: 2019,
    km: 90233,
    preco: 72000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV compacto moderno e econômico',
  },
  {
    marca: 'Land Rover',
    modelo: 'Range Rover Evoque',
    versao: '2.0 PRESTIGE 4WD 16V',
    ano: 2012,
    km: 133866,
    preco: 95000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV premium Land Rover, design sofisticado',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_654_1-1.jpg',
  },
  {
    marca: 'Renault',
    modelo: 'Captur',
    versao: '1.6 16V SCE INTENSE X-TRONIC',
    ano: 2019,
    km: 84550,
    preco: 68000,
    cor: 'Laranja',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV compacto moderno e estiloso',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_679_1-1.jpg',
  },
  {
    marca: 'Renault',
    modelo: 'Duster',
    versao: '2.0 16V DYNAMIQUE',
    ano: 2016,
    km: 86814,
    preco: 58000,
    cor: 'Cinza',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV robusto, ideal para aventuras',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_725_1-1.jpg',
  },
  {
    marca: 'Renault',
    modelo: 'Kwid',
    versao: '1.0 12V SCE ZEN',
    ano: 2018,
    km: 119123,
    preco: 35000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: false,
    descricao: 'Compacto econômico, ideal para cidade',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_753_1-1.jpg',
  },
  {
    marca: 'Toyota',
    modelo: 'Corolla',
    versao: '2.0 XEI 16V',
    ano: 2016,
    km: 121152,
    preco: 68000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Sedan médio, referência em qualidade',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_757_1-1.jpg',
  },
  {
    marca: 'Volkswagen',
    modelo: 'Fox',
    versao: 'CL 1.6',
    ano: 2016,
    km: 95000,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'Compacto Volkswagen, econômico',
  },
  {
    marca: 'Volkswagen',
    modelo: 'Fusca',
    versao: '1300',
    ano: 1975,
    km: 180010,
    preco: 35000,
    cor: 'Azul',
    carroceria: 'Sedan',
    combustivel: 'Gasolina',
    cambio: 'Manual',
    arCondicionado: false,
    direcaoHidraulica: false,
    airbag: false,
    abs: false,
    descricao: 'Clássico Fusca, colecionador',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_351_1-1.jpg',
  },
  {
    marca: 'Volkswagen',
    modelo: 'T-Cross',
    versao: '1.4 250 TSI TOTAL HIGHLINE',
    ano: 2025,
    km: 33000,
    preco: 115000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    descricao: 'SUV moderno, completo e tecnológico',
  },
];
