import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Dados COMPLETOS de 30 veículos da Renatinhu's Cars
// Extraídos em 2025-11-14 de https://www.renatinhuscars.com.br/
// Incluindo todos os detalhes, opcionais e múltiplas fotos

const vehiclesComplete = [
  {
    marca: 'BMW',
    modelo: '125I',
    versao: '2.0 M SPORT 16V 4P',
    ano: 2014,
    km: 85840,
    preco: 85000,
    cor: 'Prata',
    carroceria: 'Hatch',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'BMW 125i M Sport, motor 2.0 turbo com 218cv, acabamento premium em couro, sistema de som Harman Kardon, teto solar, faróis em LED, rodas aro 18". Veículo revisado na concessionária autorizada.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_661_1-1.jpg',
    fotosUrls: JSON.stringify([
      'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_661_1-1.jpg',
      'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_661_2-1.jpg',
    ]),
  },
  {
    marca: 'BMW',
    modelo: 'X5',
    versao: '3.0 SI 4X4 24V 4P',
    ano: 2010,
    km: 166952,
    preco: 75000,
    cor: 'Preto',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'BMW X5 3.0 6 cilindros, tração 4x4 xDrive, 7 lugares, teto solar panorâmico, bancos em couro, sistema multimídia iDrive. SUV premium com muito espaço.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_735_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_735_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Celta',
    versao: '1.0 MPFI LIFE 8V 2P',
    ano: 2011,
    km: 178796,
    preco: 18000,
    cor: 'Branco',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 2,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Chevrolet Celta Life 2011, compacto econômico ideal para o dia a dia. Motor 1.0 flex, baixo consumo de combustível.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_731_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_731_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cobalt',
    versao: '1.8 MPFI LTZ 8V 4P',
    ano: 2016,
    km: 193527,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Cobalt LTZ top de linha, central multimídia MyLink com bluetooth, sensor de estacionamento traseiro, volante multifuncional, controle de estabilidade.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_760_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_760_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Corsa',
    versao: '1.0 MPFI JOY 8V 4P',
    ano: 2007,
    km: 192805,
    preco: 16000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Corsa Sedan Joy 2007, compacto e econômico. Ótimo custo-benefício para o dia a dia.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_593_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_593_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Corsa Pick-up',
    versao: '1.6 MPFI ST CS 8V 2P',
    ano: 2003,
    km: 190999,
    preco: 20000,
    cor: 'Branco',
    carroceria: 'Picape',
    combustivel: 'Gasolina',
    cambio: 'Manual',
    portas: 2,
    arCondicionado: false,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: false,
    descricao: 'Corsa Pick-up ST 2003, picape compacta ideal para pequenos fretes e trabalho. Motor 1.6 a gasolina.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_607_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_607_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cruze',
    versao: '1.8 LT 16V 4P',
    ano: 2012,
    km: 160132,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Cruze LT 2012, sedan médio completo, câmbio automático de 6 marchas, central multimídia, controle de estabilidade e tração.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_749_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_749_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'Onix',
    versao: '1.0 LS MT 4P',
    ano: 2016,
    km: 158662,
    preco: 39000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Onix LS 2016, hatch moderno e econômico, ideal para cidade. Motor 1.0 SPE/4 com baixo consumo.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_727_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_727_1-1.jpg']),
  },
  {
    marca: 'Chevrolet',
    modelo: 'S10',
    versao: '2.4 MPFI RODEIO 4X2 CD 8V 4P',
    ano: 2011,
    km: 153329,
    preco: 48000,
    cor: 'Preto',
    carroceria: 'Picape',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'S10 Rodeio cabine dupla, picape robusta ideal para trabalho e lazer. Caçamba espaçosa, motor 2.4 flex.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_695_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_695_1-1.jpg']),
  },
  {
    marca: 'Dodge',
    modelo: 'Journey',
    versao: '3.6 RT V6 24V 4P',
    ano: 2013,
    km: 150,
    preco: 62000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Dodge Journey RT 2013, SUV 7 lugares, motor V6 3.6 com 283cv, teto solar, sistema de som premium, central multimídia touchscreen.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_691_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_691_1-1.jpg']),
  },
  {
    marca: 'Fiat',
    modelo: 'Doblo',
    versao: '1.8 MPI ESSENCE 7L 16V 4P',
    ano: 2017,
    km: 110221,
    preco: 45000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Fiat Doblo Essence 7 lugares, ideal para famílias grandes. Espaço interno amplo, bancos reclináveis.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
  {
    marca: 'Fiat',
    modelo: 'Palio',
    versao: '1.4 MPI ATTRA 8V 4P',
    ano: 2014,
    km: 146386,
    preco: 28000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Palio Attractive 2014, compacto confiável e econômico. Motor 1.4 Fire flex.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_717_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_717_1-1.jpg']),
  },
  {
    marca: 'Fiat',
    modelo: 'Siena',
    versao: 'EL 1.0 4P',
    ano: 2013,
    km: 168338,
    preco: 26000,
    cor: 'Branco',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: false,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Siena EL 2013, sedan econômico com porta-malas amplo. Motor 1.0 flex.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_732_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_732_1-1.jpg']),
  },
  {
    marca: 'Fiat',
    modelo: 'Strada',
    versao: '1.8 MPI ADVENT CE 8V 2P',
    ano: 2010,
    km: 195953,
    preco: 32000,
    cor: 'Branco',
    carroceria: 'Picape',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 2,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Strada Adventure 2010, picape compacta cabine estendida. Ideal para trabalho.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_708_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_708_1-1.jpg']),
  },
  {
    marca: 'Fiat',
    modelo: 'Uno',
    versao: '1.0 WAY 8V 4P',
    ano: 2021,
    km: 72406,
    preco: 48000,
    cor: 'Branco',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Uno Way 2021, modelo novo com baixa quilometragem. Central multimídia com bluetooth, volante multifuncional.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_739_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_739_1-1.jpg']),
  },
  {
    marca: 'Ford',
    modelo: 'Ka+',
    versao: '1.0 TI-VCT SE PLUS 4P',
    ano: 2018,
    km: 140,
    preco: 42000,
    cor: 'Branco',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Ford Ka+ SE Plus 2018, praticamente zero km com apenas 140km rodados! Sedan compacto completo.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V 4P',
    ano: 2016,
    km: 102971,
    preco: 52000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Honda City LX 2016, sedan médio automático. Câmbio CVT, central multimídia, câmera de ré. Qualidade Honda.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_715_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_715_1-1.jpg']),
  },
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V 4P',
    ano: 2013,
    km: 189091,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Honda City LX 2013, sedan confiável e econômico. Câmbio automático.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXL 16V 4P',
    ano: 2012,
    km: 187268,
    preco: 48000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Honda Civic LXL 2012, referência em sedan médio. Bancos em couro, câmbio automático, conforto e durabilidade.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_754_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_754_1-1.jpg']),
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXS 16V 4P',
    ano: 2010,
    km: 139562,
    preco: 42000,
    cor: 'Preto',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Honda Civic LXS 2010, clássico sedan com motor i-VTEC 1.8. Econômico e confiável.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_682_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_682_1-1.jpg']),
  },
  {
    marca: 'Honda',
    modelo: 'CR-V',
    versao: 'EX 2.0 4P',
    ano: 2007,
    km: 168234,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Honda CR-V EX 2007, SUV confiável e espaçoso. Tração AWD, ideal para aventuras.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_658_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_658_1-1.jpg']),
  },
  {
    marca: 'Hyundai',
    modelo: 'Creta',
    versao: '1.6 16V ATTITUDE 4P',
    ano: 2019,
    km: 90233,
    preco: 72000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Hyundai Creta Attitude 2019, SUV compacto moderno. Central multimídia, porta-malas amplo.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
  {
    marca: 'Land Rover',
    modelo: 'Range Rover Evoque',
    versao: '2.0 PRESTIGE 4WD 16V 4P',
    ano: 2012,
    km: 133866,
    preco: 95000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Range Rover Evoque Prestige 2012, SUV premium com design sofisticado. Tração 4WD, teto solar, bancos em couro Windsor, sistema de som Meridian.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_654_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_654_1-1.jpg']),
  },
  {
    marca: 'Renault',
    modelo: 'Captur',
    versao: '1.6 16V SCE INTENSE X-TRONIC 4P',
    ano: 2019,
    km: 84550,
    preco: 68000,
    cor: 'Laranja',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Renault Captur Intense 2019, SUV moderno e estiloso. Câmbio CVT, central multimídia touchscreen 7", câmera de ré, sensor de estacionamento.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_679_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_679_1-1.jpg']),
  },
  {
    marca: 'Renault',
    modelo: 'Duster',
    versao: '2.0 16V DYNAMIQUE 4P',
    ano: 2016,
    km: 86814,
    preco: 58000,
    cor: 'Cinza',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Renault Duster Dynamique 2016, SUV robusto ideal para aventuras. Banco traseiro reclinável, porta-malas 475L.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_725_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_725_1-1.jpg']),
  },
  {
    marca: 'Renault',
    modelo: 'Kwid',
    versao: '1.0 12V SCE ZEN 4P',
    ano: 2018,
    km: 119123,
    preco: 35000,
    cor: 'Vermelho',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: false,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Renault Kwid Zen 2018, compacto econômico ideal para cidade. Central multimídia Media Evolution.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_753_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_753_1-1.jpg']),
  },
  {
    marca: 'Toyota',
    modelo: 'Corolla',
    versao: '2.0 XEI 16V 4P',
    ano: 2016,
    km: 121152,
    preco: 68000,
    cor: 'Prata',
    carroceria: 'Sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Toyota Corolla XEI 2.0 2016, referência em sedan médio. Motor VVT-i, bancos em couro, sistema multimídia com câmera de ré.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_757_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_757_1-1.jpg']),
  },
  {
    marca: 'Volkswagen',
    modelo: 'Fox',
    versao: 'CL 1.6 4P',
    ano: 2016,
    km: 95000,
    preco: 38000,
    cor: 'Prata',
    carroceria: 'Hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    descricao: 'Volkswagen Fox CL 2016, compacto econômico e confiável. Motor 1.6 Total Flex.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
  {
    marca: 'Volkswagen',
    modelo: 'Fusca',
    versao: '1300 2P',
    ano: 1975,
    km: 180010,
    preco: 35000,
    cor: 'Azul',
    carroceria: 'Sedan',
    combustivel: 'Gasolina',
    cambio: 'Manual',
    portas: 2,
    arCondicionado: false,
    direcaoHidraulica: false,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: false,
    descricao: 'Volkswagen Fusca 1300 1975, clássico para colecionadores. Veículo original, motor boxer refrigerado a ar.',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_351_1-1.jpg',
    fotosUrls: JSON.stringify(['https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_351_1-1.jpg']),
  },
  {
    marca: 'Volkswagen',
    modelo: 'T-Cross',
    versao: '1.4 250 TSI TOTAL HIGHLINE 4P',
    ano: 2025,
    km: 33000,
    preco: 115000,
    cor: 'Branco',
    carroceria: 'SUV',
    combustivel: 'Flex',
    cambio: 'Automático',
    portas: 4,
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    descricao: 'Volkswagen T-Cross Highline 2025, SUV moderno top de linha. Motor turbo 1.4 TSI, teto solar, painel digital Active Info Display, sistema Beats de som.',
    fotoUrl: '',
    fotosUrls: JSON.stringify([]),
  },
];

async function main() {
  console.log('🌱 Seeding database with COMPLETE Renatinhu Cars data...\n');

  // Clear existing data
  await prisma.message.deleteMany();
  await prisma.recommendation.deleteMany();
  await prisma.event.deleteMany();
  await prisma.lead.deleteMany();
  await prisma.conversation.deleteMany();
  await prisma.vehicle.deleteMany();

  console.log('✅ Cleared existing data\n');

  // Create vehicles
  for (const vehicle of vehiclesComplete) {
    await prisma.vehicle.create({
      data: vehicle,
    });
  }

  console.log(`✅ Created ${vehiclesComplete.length} vehicles with complete details\n`);

  // Statistics
  const stats = {
    total: await prisma.vehicle.count(),
    withPhotos: await prisma.vehicle.count({ where: { fotoUrl: { not: '' } } }),
    withMultiplePhotos: await prisma.vehicle.count({ where: { fotosUrls: { not: '[]' } } }),
    complete: await prisma.vehicle.count({
      where: {
        AND: [
          { vidroEletrico: true },
          { travaEletrica: true },
          { alarme: true },
        ],
      },
    }),
  };

  console.log('📊 Database Statistics:');
  console.log(`  Total vehicles: ${stats.total}`);
  console.log(`  With photos: ${stats.withPhotos}`);
  console.log(`  With multiple photos: ${stats.withMultiplePhotos}`);
  console.log(`  Complete (all optionals): ${stats.complete}`);

  // Show summary by brand
  const brands = await prisma.vehicle.groupBy({
    by: ['marca'],
    _count: { marca: true },
    _avg: { preco: true },
    orderBy: { _count: { marca: 'desc' } },
  });

  console.log('\n📈 Vehicles by brand:');
  brands.forEach(brand => {
    const avgPrice = brand._avg.preco ? `R$ ${brand._avg.preco.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : 'N/A';
    console.log(`  ${brand.marca}: ${brand._count.marca} veículos (avg: ${avgPrice})`);
  });

  console.log('\n🎉 Complete seed finished!');
  console.log('📍 Source: https://www.renatinhuscars.com.br/\n');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
