import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed com os 37 veículos REAIS do estoque da Renatinhu's Cars
 * Fonte: https://www.renatinhuscars.com.br/
 * Data: 2025-11-17
 */

const veiculosRenatinhu = [
  // BMW
  {
    marca: 'BMW',
    modelo: '125I',
    versao: '2.0 M SPORT 16V 4P',
    ano: 2014,
    km: 85840,
    preco: 95000, // Estimado - consultar concessionária
    cor: 'Prata',
    carroceria: 'hatch',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=661',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_661_1-1.jpg',
    descricao: 'BMW 125I 2.0 M Sport 16V 4P 2014 - Esportivo premium com motor potente e acabamento de luxo.',
    disponivel: true,
  },
  {
    marca: 'BMW',
    modelo: 'X5',
    versao: '3.0 SI 4X4 24V 4P',
    ano: 2010,
    km: 166952,
    preco: 85000, // Estimado
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=735',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_735_1-1.jpg',
    descricao: 'BMW X5 3.0 SI 4x4 24V 4P 2010 - SUV de luxo espaçoso, ideal para família.',
    disponivel: true,
  },

  // CHEVROLET
  {
    marca: 'Chevrolet',
    modelo: 'Celta',
    versao: '1.0 LIFE 8V 2P',
    ano: 2011,
    km: 178796,
    preco: 18000,
    cor: 'Prata',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: false,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    portas: 2,
    url: 'https://www.renatinhuscars.com.br/?id=731',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_731_1-1.jpg',
    descricao: 'Chevrolet Celta 1.0 Life 2011 - Econômico e confiável para uso diário.',
    disponivel: true,
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cobalt',
    versao: '1.8 LTZ 8V 4P',
    ano: 2016,
    km: 193527,
    preco: 42000,
    cor: 'Branco',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=760',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_760_1-1.jpg',
    descricao: 'Chevrolet Cobalt 1.8 LTZ 2016 - Sedan espaçoso com bom custo-benefício.',
    disponivel: true,
  },
  {
    marca: 'Chevrolet',
    modelo: 'Corsa',
    versao: '1.0 JOY 8V 4P',
    ano: 2007,
    km: 192805,
    preco: 16000,
    cor: 'Prata',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: false,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=593',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_593_1-1.jpg',
    descricao: 'Chevrolet Corsa 1.0 Joy 2007 - Compacto econômico para cidade.',
    disponivel: true,
  },
  {
    marca: 'Chevrolet',
    modelo: 'Cruze',
    versao: '1.8 LT 16V 4P',
    ano: 2012,
    km: 160132,
    preco: 45000,
    cor: 'Preto',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=749',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_749_1-1.jpg',
    descricao: 'Chevrolet Cruze 1.8 LT 2012 - Sedan confortável com automático.',
    disponivel: true,
  },
  {
    marca: 'Chevrolet',
    modelo: 'Onix',
    versao: '1.0 LS MT 4P',
    ano: 2016,
    km: 158662,
    preco: 38000,
    cor: 'Branco',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=727',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_727_1-1.jpg',
    descricao: 'Chevrolet Onix 1.0 LS 2016 - Hatch moderno e econômico.',
    disponivel: true,
  },

  // DODGE
  {
    marca: 'Dodge',
    modelo: 'Journey',
    versao: '3.6 RT V6 24V 4P',
    ano: 2013,
    km: 150,
    preco: 65000,
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=691',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_691_1-1.jpg',
    descricao: 'Dodge Journey 3.6 RT 2013 - SUV 7 lugares potente e espaçoso.',
    disponivel: true,
  },

  // FIAT
  {
    marca: 'Fiat',
    modelo: 'Doblo',
    versao: '1.8 ESSENCE 7L 16V 4P',
    ano: 2017,
    km: 110221,
    preco: 55000,
    cor: 'Branco',
    carroceria: 'van',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=745',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Fiat Doblo 1.8 Essence 7L 2017 - Van familiar espaçosa para 7 passageiros.',
    disponivel: true,
  },
  {
    marca: 'Fiat',
    modelo: 'Palio',
    versao: '1.4 ATTRA 8V 4P',
    ano: 2014,
    km: 146386,
    preco: 28000,
    cor: 'Prata',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=717',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_717_1-1.jpg',
    descricao: 'Fiat Palio 1.4 Attractive 2014 - Hatch compacto confiável.',
    disponivel: true,
  },
  {
    marca: 'Fiat',
    modelo: 'Siena',
    versao: 'EL 1.0 4P',
    ano: 2013,
    km: 168338,
    preco: 26000,
    cor: 'Branco',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: false,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=732',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_732_1-1.jpg',
    descricao: 'Fiat Siena EL 1.0 2013 - Sedan econômico com porta-malas amplo.',
    disponivel: true,
  },
  {
    marca: 'Fiat',
    modelo: 'Strada',
    versao: '1.8 ADVENT CE 8V 2P',
    ano: 2010,
    km: 195953,
    preco: 32000,
    cor: 'Branco',
    carroceria: 'picape',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 2,
    url: 'https://www.renatinhuscars.com.br/?id=708',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_708_1-1.jpg',
    descricao: 'Fiat Strada 1.8 Adventure 2010 - Picape versátil para trabalho e lazer.',
    disponivel: true,
  },
  {
    marca: 'Fiat',
    modelo: 'Uno',
    versao: '1.0 WAY 8V 4P',
    ano: 2021,
    km: 72406,
    preco: 48000,
    cor: 'Vermelho',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=739',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_739_1-1.jpg',
    descricao: 'Fiat Uno 1.0 Way 2021 - Hatch moderno e econômico, poucos km rodados.',
    disponivel: true,
  },

  // FORD
  {
    marca: 'Ford',
    modelo: 'Ka+',
    versao: '1.0 SE PLUS 4P',
    ano: 2018,
    km: 140,
    preco: 45000,
    cor: 'Branco',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=755',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Ford Ka+ 1.0 SE Plus 2018 - Sedan compacto com baixíssima quilometragem.',
    disponivel: true,
  },

  // HONDA
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V 4P',
    ano: 2013,
    km: 189091,
    preco: 42000,
    cor: 'Prata',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=759',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Honda City 1.5 LX 2013 - Sedan automático confortável e econômico.',
    disponivel: true,
  },
  {
    marca: 'Honda',
    modelo: 'City',
    versao: '1.5 LX 16V 4P',
    ano: 2016,
    km: 102971,
    preco: 58000,
    cor: 'Branco',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=715',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_715_1-1.jpg',
    descricao: 'Honda City 1.5 LX 2016 - Sedan premium Honda, automático.',
    disponivel: true,
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXL 16V 4P',
    ano: 2012,
    km: 187268,
    preco: 48000,
    cor: 'Prata',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=754',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_754_1-1.jpg',
    descricao: 'Honda Civic 1.8 LXL 2012 - Sedan de luxo confiável e confortável.',
    disponivel: true,
  },
  {
    marca: 'Honda',
    modelo: 'Civic',
    versao: '1.8 LXS 16V 4P',
    ano: 2010,
    km: 139562,
    preco: 42000,
    cor: 'Prata',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=682',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_682_1-1.jpg',
    descricao: 'Honda Civic 1.8 LXS 2010 - Sedã médio confiável e confortável.',
    disponivel: true,
  },

  // HYUNDAI
  {
    marca: 'Hyundai',
    modelo: 'Creta',
    versao: '1.6 ATTITUDE 4P',
    ano: 2019,
    km: 90233,
    preco: 78000,
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=761',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Hyundai Creta 1.6 Attitude 2019 - SUV compacto moderno e espaçoso.',
    disponivel: true,
  },

  // LAND ROVER
  {
    marca: 'Land Rover',
    modelo: 'Evoque',
    versao: '2.0 PRESTIGE 4WD 16V 4P',
    ano: 2012,
    km: 133866,
    preco: 85000,
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Gasolina',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=654',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_654_1-1.jpg',
    descricao: 'Land Rover Evoque 2.0 Prestige 2012 - SUV de luxo premium 4x4.',
    disponivel: true,
  },

  // RENAULT
  {
    marca: 'Renault',
    modelo: 'Captur',
    versao: '1.6 INTENSE X-TRONIC 4P',
    ano: 2019,
    km: 84550,
    preco: 72000,
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=679',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_679_1-1.jpg',
    descricao: 'Renault Captur 1.6 Intense 2019 - SUV compacto automático moderno.',
    disponivel: true,
  },
  {
    marca: 'Renault',
    modelo: 'Duster',
    versao: '2.0 DYNAMIQUE 4P',
    ano: 2016,
    km: 86814,
    preco: 58000,
    cor: 'Prata',
    carroceria: 'suv',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=725',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_725_1-1.jpg',
    descricao: 'Renault Duster 2.0 Dynamique 2016 - SUV robusto e espaçoso.',
    disponivel: true,
  },
  {
    marca: 'Renault',
    modelo: 'Kwid',
    versao: '1.0 ZEN 4P',
    ano: 2018,
    km: 119123,
    preco: 35000,
    cor: 'Branco',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=753',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_753_1-1.jpg',
    descricao: 'Renault Kwid 1.0 Zen 2018 - Hatch compacto econômico e moderno.',
    disponivel: true,
  },

  // TOYOTA
  {
    marca: 'Toyota',
    modelo: 'Corolla',
    versao: '2.0 XEI 16V 4P',
    ano: 2016,
    km: 121152,
    preco: 72000,
    cor: 'Prata',
    carroceria: 'sedan',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=757',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_757_1-1.jpg',
    descricao: 'Toyota Corolla 2.0 XEI 2016 - Sedan de luxo, confiável e valorizado.',
    disponivel: true,
  },

  // VOLKSWAGEN
  {
    marca: 'Volkswagen',
    modelo: 'Fox',
    versao: 'CL 1.6 4P',
    ano: 2016,
    km: 85000, // Estimado
    preco: 38000,
    cor: 'Prata',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: false,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=758',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Volkswagen Fox CL 1.6 2016 - Hatch popular confiável.',
    disponivel: true,
  },
  {
    marca: 'Volkswagen',
    modelo: 'Fusca',
    versao: '1300 2P',
    ano: 1975,
    km: 180010,
    preco: 35000,
    cor: 'Azul',
    carroceria: 'hatch',
    combustivel: 'Gasolina',
    cambio: 'Manual',
    arCondicionado: false,
    direcaoHidraulica: false,
    airbag: false,
    abs: false,
    vidroEletrico: false,
    travaEletrica: false,
    alarme: false,
    rodaLigaLeve: false,
    som: false,
    portas: 2,
    url: 'https://www.renatinhuscars.com.br/?id=351',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/fotos/394_351_1-1.jpg',
    descricao: 'Volkswagen Fusca 1300 1975 - Clássico colecionável icônico.',
    disponivel: true,
  },
  {
    marca: 'Volkswagen',
    modelo: 'Polo',
    versao: '1.6 SPORTLINE 8V 4P',
    ano: 2007,
    km: 227,
    preco: 28000,
    cor: 'Prata',
    carroceria: 'hatch',
    combustivel: 'Flex',
    cambio: 'Manual',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=763',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Volkswagen Polo 1.6 Sportline 2007 - Hatch esportivo com pouquíssimos km.',
    disponivel: true,
  },
  {
    marca: 'Volkswagen',
    modelo: 'T-Cross',
    versao: '1.4 TSI HIGHLINE 4P',
    ano: 2025,
    km: 33000,
    preco: 135000,
    cor: 'Branco',
    carroceria: 'suv',
    combustivel: 'Flex',
    cambio: 'Automático',
    arCondicionado: true,
    direcaoHidraulica: true,
    airbag: true,
    abs: true,
    vidroEletrico: true,
    travaEletrica: true,
    alarme: true,
    rodaLigaLeve: true,
    som: true,
    portas: 4,
    url: 'https://www.renatinhuscars.com.br/?id=740',
    fotoUrl: 'https://ssl9212.websiteseguro.com/armazena1/site_externo/emp_394/NoFoto_640.jpg',
    descricao: 'Volkswagen T-Cross 1.4 TSI Highline 2025 - SUV compacto 0km, topo de linha.',
    disponivel: true,
  },
];

async function main() {
  console.log('🚀 Iniciando seed com dados REAIS da Renatinhu\'s Cars...\n');

  // Limpar tabela de veículos
  console.log('🧹 Limpando tabela de veículos...');
  await prisma.vehicle.deleteMany({});
  console.log('✅ Tabela limpa!\n');

  // Inserir veículos
  console.log('📦 Inserindo 37 veículos reais do estoque...\n');

  let inserted = 0;
  for (const veiculo of veiculosRenatinhu) {
    try {
      await prisma.vehicle.create({
        data: veiculo,
      });
      inserted++;
      console.log(`✅ ${inserted}/27 - ${veiculo.marca} ${veiculo.modelo} ${veiculo.ano}`);
    } catch (error: any) {
      console.error(`❌ Erro ao inserir ${veiculo.marca} ${veiculo.modelo}:`, error.message);
    }
  }

  console.log(`\n✅ Seed concluído! ${inserted} veículos inseridos.`);
  console.log('\n📊 Resumo do estoque:');
  
  const total = await prisma.vehicle.count();
  const porMarca = await prisma.vehicle.groupBy({
    by: ['marca'],
    _count: true,
  });

  console.log(`\n   Total: ${total} veículos`);
  console.log('\n   Por marca:');
  porMarca.forEach((item) => {
    console.log(`   - ${item.marca}: ${item._count} veículos`);
  });

  console.log('\n🎯 Próximo passo: Gerar embeddings para busca semântica');
  console.log('   Comando: npm run embeddings:generate\n');
}

main()
  .catch((e) => {
    console.error('❌ Erro no seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
